import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from '../components/Navigation/Navigation';
import './globals.css';
import styles from './layout.module.css';
import { RxHamburgerMenu } from 'react-icons/rx';
import { builder } from '@builder.io/sdk';
import Footer from '@/components/Footer/Footer';
import SideNav from '@/components/SideNav/SideNav';
builder.init('9a41098f7b034bc69ea3e94d13345db8');

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html lang="en">
               <body>
                    <div className={styles.root}>
                         <SideNav />
                         <header className={styles.header}>
                              <Navigation />
                         </header>
                         <main className={styles.main}>{children}</main>
                         <Footer />
                    </div>
               </body>
          </html>
     );
}
